# --------------------- #
#    Generation File    #
# --------------------- #

# Other generation files to import. (Example: intensive_apps -> ~/.config/rebos/imports/intensive_apps.toml)
imports = [
  "intel",
  "sddm",
  "fonts",
  "niri",
  "thunar",
  "neovim",
  "audio",
  "shell",
  "services",
  "security",
  "utilities",
  "apps",
  'quickshell',
]

# Packages to be installed via the native package manager.
[managers.system]
items = [
  "git",
  "flatpak",
]

# Packages to be installed via Flatpak.
[managers.flatpak]
items = [
  "com.github.tchx84.Flatseal",
]

# Packages to be installed via Cargo.
[managers.cargo]
items = [
  # "bacon",
]
