[managers.system]
items = [
  "niri",
  "xwayland-satellite",
  'matugen-bin',
  'wallust',
  'python-pywal16',
  'wpgtk',
  "kitty",
  "alacritty",
  "graphite-gtk-theme-black-git",
  "papirus-icon-theme",
  "tela-circle-icon-theme-all",
  "zen-browser-bin",
  "waybar",
  "swaync",
  "swww",
  "nwg-look",
  'qt5ct',
  'qt6ct',
  "rofi-lbonn-wayland-git",
  "qt5-wayland",
  "qt6-wayland",
  'kvantum',
  "cliphist",
  "wlsunset",
  "wl-clipboard",
  "brightnessctl",
  'xfce-polkit',
  "xdg-utils",
  "flatpak-xdg-utils",
  "libnotify",
]
