[managers.system]
items = [
  "thunar",
  "thunar-volman",
  "thunar-archive-plugin",
  "thunar-media-tags-plugin",
  "thunar-shares-plugin",
  "thunar-vcs-plugin",
  'tumbler',
  'xarchiver',
  'unzip',
  'zip',
  'tar',
  '7zip',
  'unrar',
  "ffmpegthumbnailer",
  "gvfs",
  "gvfs-mtp",
  "gvfs-nfs",
]
